version: '3'

services:
  metabase:
    container_name: 'metabase'
    image: 'metabase/metabase'
    restart: 'always'
    env_file:
      - metabase.env
    ports:
      - '3000:3000'
    volumes:
      - metabase_data:/metabase-data
    networks:
      - metabase

volumes:
  metabase_data:
    driver: 'local'

networks:
  metabase:
    driver: 'bridge'
